name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: sudo apt install -y gcc g++ gdb make cmake libwxgtk3.0-gtk3-dev libcurl4-openssl-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make all
